{% set name = "speedy-antlr-tool" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/speedy-antlr-tool-{{ version }}.tar.gz
  sha256: 1d1f6776bf66e6d9f8b01c5b84df239a58a9abb1d4bf22ae33a82666313df4fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - antlr4-python3-runtime >=4.10,<4.14
    - jinja2

test:
  imports:
    - speedy_antlr_tool
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/amykyta3/speedy-antlr-tool
  summary: Generate an accelerator extension that makes your Antlr parser in Python super-fast!
  dev_url: https://github.com/amykyta3/speedy-antlr-tool
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch
