schema_version: 1

context:
  name: speedy-antlr-tool
  version: 1.4.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/speedy-antlr-tool-${{ version }}.tar.gz
  sha256: 1d1f6776bf66e6d9f8b01c5b84df239a58a9abb1d4bf22ae33a82666313df4fa

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - antlr4-python3-runtime >=4.10,<4.14
    - jinja2

tests:
  - python:
      imports:
        - speedy_antlr_tool
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Generate an accelerator extension that makes your Antlr parser in Python super-fast!
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/amykyta3/speedy-antlr-tool
  repository: https://github.com/amykyta3/speedy-antlr-tool

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch
